version: '3.7'
services:
  jenkins:
    image: yallalabs/jenkins:centos
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Dhudson.footerURL=http://yallalabs.com
      - JENKINS_USER=diarmaid
      - JENKINS_PASS=password
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      traefik:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
         condition: on-failure
      placement:
        constraints:
          - node.role == worker
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://localhost:8080/login || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - traefik.port=8080
      - traefik.port=50000
      - traefik.frontend.rule=Host:jenkins.diarmaiddeburca.de
      - traefik.docker.network=traefik
      - traefik.frontend.whitelist.SourceRange=127.0.0.1

volumes:
  jenkins_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/jenkinsdata"

networks:
  traefik:
    external: true